name: CI MacOS

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    name: Build & Test on macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Pandoc
      run: brew install pandoc
    - name: Install Pdflatex
      run: curl https://ctan.crest.fr/tex-archive/systems/mac/mactex/BasicTeX.pkg -o ./BasicTeX.pkg && sudo installer -pkg ./BasicTeX.pkg -target /
    - name: Check pdflatex
      run: pdflatex -version
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
