name: CI Linux

on:
  push:
    branches: [ develop, master ]
jobs:
  build-executable:
    name: Build, Test and compile executable on Linux
    runs-on: ubuntu-latest
    container:
      image: ombrelin/linux-net6-pandoc
    steps:
    - uses: actions/checkout@v2
    - name: Install dotnet-deb
      run: dotnet tool install --global dotnet-deb && cd PandocGui && dotnet deb install
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build Deb
      run: cd PandocGui && dotnet deb -c Release -r linux-x64
    - name: Save executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pandoc-gui-executable
        path: PandocGui\bin\Release\net6.0\PandocGui.1.0.0.deb
