name: CI Linux

on:
  push:
    branches: [ develop, master ]
jobs:
  build-executable:
    name: Build, Test and compile executable on Linux
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build Executable
      run: cd src/PandocGui && dotnet publish -c Release --runtime linux-x64 -p:PublishReadyToRun=true --self-contained --output ./dist/linux-x64
    - name: Save executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pandoc-gui-executable
        path: src/PandocGui/dist/linux-x64/
