name: CI Linux

on:
  push:
    branches: [ develop, master ]
jobs:
  build-executable:
    name: Build, Test and compile executable on Linux
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Install dotnet deb
      run: dotnet tool install --global dotnet-deb && cd src/PandocGui && dotnet deb install
    - name: Build deb package
      run: cd src/PandocGui && dotnet deb -c Release -f net6.0 -o dist/linux-x64
    - name: Save deb package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pandoc-gui
        path: src/PandocGui/dist/linux-x64/
