name: CI Windows

on:
  push:
    branches: [ develop, master ]

jobs:
  build-executable:
    name: Build, Test and publish executable on windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Build Executable
        run: cd src/PandocGui && dotnet publish --runtime win-x64 --configuration Release -p:PublishSingleFile=true --self-contained true --output C:\temp\pandocgui
      - name: Compile Installer
        run: iscc installers/windows/installer.iss /dBuildNumber=${{github.run_number}} /dMyAppURL=https://github.com/${{github.repository}}
      - name: Save Installer as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pandoc-gui-setup
          path: C:\temp\pandocgui\pandoc-gui-setup.exe